### ISSUE TITLE
System tables: Show 'committed-at' value in a nicer format

### ISSUE THREAD

**Issue by cmathiesen** [ExpediaGroup/hiveberg#22]
In our current snapshot system table the results for the `committed-at` column are displayed in as an epoch timestamp like `1234567890` which isn't very user-friendly. 

The Presto implementation for system tables display the timestamp in a more human-readable format: `2020-01-06 09:10:13.354 UTC`. 

We should implement something similar in our system tables

**Comment by massdosage** [comment]
Closing before archiving this project.
